authDomain: auth.secure-proxy.wtrn.ru:8443
sessions:
  cookieDomain: .secure-proxy.wtrn.ru
  cookieName: SECURE_PROXY_SESSION
  ttl: 180s
users:
  - username: user1
    totpSecret: DU2DGNS3ALWXIGLWK7ZVBXHL7ZN6ZCAC
    availableDomains:
      - restaurant.secure-proxy.wtrn.ru
upstreams:
  - host: google.secure-proxy.wtrn.ru # должен быть поддоменом .secure-proxy.lan, чтобы мы могли увидеть куку
    destination: https://google.com # куда проксировать успешно аутентифицированные запросы